In [1]:
import numpy as np # numerical computation
import pandas as pd # data wrangling
import matplotlib.pyplot as plt # plotting package
import matplotlib as mpl # add'1 plotting functionality
mpl.rcParams['figure.dpi'] = 400 # high res figures

In [2]:
medal_distribution_2024 = pd.read_csv('../data/raw/medalists_data_raw.csv')
medal_distribution_2024.head()

,medal_date,medal_type,medal_code,name,gender,country_code,country,country_long,nationality_code,nationality,...,team,team_gender,discipline,event,event_type,url_event,birth_date,code_athlete,code_team,is_medallist
0,2024-07-27,Gold Medal,1.0,EVENEPOEL Remco,Male,BEL,Belgium,Belgium,BEL,Belgium,...,NaN,NaN,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,2000-01-25,1903136,NaN,True
1,2024-07-27,Silver Medal,2.0,GANNA Filippo,Male,ITA,Italy,Italy,ITA,Italy,...,NaN,NaN,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,1996-07-25,1923520,NaN,True
2,2024-07-27,Bronze Medal,3.0,van AERT Wout,Male,BEL,Belgium,Belgium,BEL,Belgium,...,NaN,NaN,Cycling Road,Men's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/men-s-indi...,1994-09-15,1903147,NaN,True
3,2024-07-27,Gold Medal,1.0,BROWN Grace,Female,AUS,Australia,Australia,AUS,Australia,...,NaN,NaN,Cycling Road,Women's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/women-s-in...,1992-07-07,1940173,NaN,True
4,2024-07-27,Silver Medal,2.0,HENDERSON Anna,Female,GBR,Great Britain,Great Britain,GBR,Great Britain,...,NaN,NaN,Cycling Road,Women's Individual Time Trial,ATH,/en/paris-2024/results/cycling-road/women-s-in...,1998-11-14,1912525,NaN,True

In [3]:
medal_distribution_2024 = medal_distribution_2024[['medal_date', 'medal_type', 'country',
                                                   'discipline', 'event', 'code_team']]
medal_distribution_2024.head()

,medal_date,medal_type,country,discipline,event,code_team
0,2024-07-27,Gold Medal,Belgium,Cycling Road,Men's Individual Time Trial,NaN
1,2024-07-27,Silver Medal,Italy,Cycling Road,Men's Individual Time Trial,NaN
2,2024-07-27,Bronze Medal,Belgium,Cycling Road,Men's Individual Time Trial,NaN
3,2024-07-27,Gold Medal,Australia,Cycling Road,Women's Individual Time Trial,NaN
4,2024-07-27,Silver Medal,Great Britain,Cycling Road,Women's Individual Time Trial,NaN

In [4]:
medal_distribution_2024.shape

(2315, 6)

In [5]:
duplicate_rows = medal_distribution_2024[medal_distribution_2024.duplicated()]
duplicate_rows

,medal_date,medal_type,country,discipline,event,code_team
761,2024-07-27,Gold Medal,China,Diving,Women's Synchronised 3m Springboard,DIVW3MTEAM2-CHN01
763,2024-07-27,Silver Medal,United States,Diving,Women's Synchronised 3m Springboard,DIVW3MTEAM2-USA01
765,2024-07-27,Bronze Medal,Great Britain,Diving,Women's Synchronised 3m Springboard,DIVW3MTEAM2-GBR01
767,2024-07-27,Gold Medal,France,Rugby Sevens,Men,RU7MTEAM7---FRA01
768,2024-07-27,Gold Medal,France,Rugby Sevens,Men,RU7MTEAM7---FRA01
...,...,...,...,...,...,...
2309,2024-08-10,Silver Medal,Israel,Rhythmic Gymnastics,Group All-Around,GRYW5AA-----ISR01
2311,2024-08-10,Bronze Medal,Italy,Rhythmic Gymnastics,Group All-Around,GRYW5AA-----ITA01
2312,2024-08-10,Bronze Medal,Italy,Rhythmic Gymnastics,Group All-Around,GRYW5AA-----ITA01
2313,2024-08-10,Bronze Medal,Italy,Rhythmic Gymnastics,Group All-Around,GRYW5AA-----ITA01
2314,2024-08-10,Bronze Medal,Italy,Rhythmic Gymnastics,Group All-Around,GRYW5AA-----ITA01

In [6]:
medal_distribution_2024 = medal_distribution_2024.drop_duplicates(keep='first')
medal_distribution_2024.head()

,medal_date,medal_type,country,discipline,event,code_team
0,2024-07-27,Gold Medal,Belgium,Cycling Road,Men's Individual Time Trial,NaN
1,2024-07-27,Silver Medal,Italy,Cycling Road,Men's Individual Time Trial,NaN
2,2024-07-27,Bronze Medal,Belgium,Cycling Road,Men's Individual Time Trial,NaN
3,2024-07-27,Gold Medal,Australia,Cycling Road,Women's Individual Time Trial,NaN
4,2024-07-27,Silver Medal,Great Britain,Cycling Road,Women's Individual Time Trial,NaN

In [7]:
medal_distribution_2024.shape

(1044, 6)

In [8]:
medal_distribution_2024 = medal_distribution_2024[['country', 'medal_type']]
medal_distribution_2024.head()

         country    medal_type
0        Belgium    Gold Medal
1          Italy  Silver Medal
2        Belgium  Bronze Medal
3      Australia    Gold Medal
4  Great Britain  Silver Medal

In [9]:
medal_distribution_2024 = medal_distribution_2024.pivot_table(index='country', columns='medal_type',
                                                              aggfunc='size', fill_value=0)
medal_distribution_2024

medal_type     Bronze Medal  Gold Medal  Silver Medal
country
AIN                       1           1             3
Albania                   2           0             0
Algeria                   1           2             0
Argentina                 1           1             1
Armenia                   1           0             3
...                     ...         ...           ...
Uganda                    0           1             1
Ukraine                   4           3             5
United States            42          40            44
Uzbekistan                3           8             2
Zambia                    1           0             0

[92 rows x 3 columns]

In [10]:
medal_distribution_2024 = medal_distribution_2024[['Gold Medal', 'Silver Medal', 'Bronze Medal']].copy()
medal_distribution_2024['Total Medals'] = medal_distribution_2024.sum(axis=1)
medal_distribution_2024

medal_type     Gold Medal  Silver Medal  Bronze Medal  Total Medals
country
AIN                     1             3             1             5
Albania                 0             0             2             2
Algeria                 2             0             1             3
Argentina               1             1             1             3
Armenia                 0             3             1             4
...                   ...           ...           ...           ...
Uganda                  1             1             0             2
Ukraine                 3             5             4            12
United States          40            44            42           126
Uzbekistan              8             2             3            13
Zambia                  0             0             1             1

[92 rows x 4 columns]

In [11]:
medal_distribution_2024.info()

<class 'pandas.core.frame.DataFrame'>
Index: 92 entries, AIN to Zambia
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Gold Medal    92 non-null     int64
 1   Silver Medal  92 non-null     int64
 2   Bronze Medal  92 non-null     int64
 3   Total Medals  92 non-null     int64
dtypes: int64(4)
memory usage: 3.6+ KB

In [12]:
world_population_gdp_2024 = pd.read_csv("../data/raw/world_gdp_data_raw.csv")
world_population_gdp_2024.head()

,population,id,imfGDP,unGDP,country,gdpPerCapita,continent,rank
0,345426571,840,2.878108e+13,25744100000000,United States,83320.399808,North America,1
1,1419321278,156,1.853263e+13,17963170521080,China,13057.388970,Asia,2
2,84552242,276,4.591100e+12,4076923618912,Germany,54298.974118,Europe,3
3,123753041,392,4.110450e+12,4232173916087,Japan,33214.941361,Asia,4
4,1450935791,356,3.937010e+12,3465541446546,India,2713.428137,Asia,5

In [13]:
world_population_gdp_2024 = world_population_gdp_2024[['country', 'population', 'gdpPerCapita']]
world_population_gdp_2024.head()

         country  population  gdpPerCapita
0  United States   345426571  83320.399808
1          China  1419321278  13057.388970
2        Germany    84552242  54298.974118
3          Japan   123753041  33214.941361
4          India  1450935791   2713.428137

In [14]:
world_population_gdp_2024.set_index('country', inplace=True)
world_population_gdp_2024.head()

               population  gdpPerCapita
country
United States   345426571  83320.399808
China          1419321278  13057.388970
Germany          84552242  54298.974118
Japan           123753041  33214.941361
India          1450935791   2713.428137

In [15]:
world_population_gdp_2024.info()

<class 'pandas.core.frame.DataFrame'>
Index: 212 entries, United States to Turks and Caicos Islands
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   population    212 non-null    int64
 1   gdpPerCapita  212 non-null    float64
dtypes: float64(1), int64(1)
memory usage: 5.0+ KB

In [16]:
# To merge the two dataframes, keeping all rows from medal_distribution_2024
# and only matching rows from world_population_gdp_2024:

medals_population_gdp_2024 = medal_distribution_2024.merge(world_population_gdp_2024,
                                                           left_index=True, right_index=True,
                                                           how='left')
medals_population_gdp_2024

,Gold Medal,Silver Medal,Bronze Medal,Total Medals,population,gdpPerCapita
country,,,,,,
AIN,1,3,1,5,NaN,NaN
Albania,0,0,2,2,2791765.0,9109.291076
Algeria,2,0,1,3,46814308.0,5698.685111
Argentina,1,1,1,3,45696159.0,13223.430880
Armenia,0,3,1,4,2973840.0,8543.835580
...,...,...,...,...,...,...
Uganda,1,1,0,2,50015092.0,1125.860170
Ukraine,3,5,4,12,37860221.0,4990.541392
United States,40,44,42,126,345426571.0,83320.399808
Uzbekistan,8,2,3,13,36361859.0,2693.921672
Zambia,0,0,1,1,21314956.0,1401.457268

In [17]:
medals_population_gdp_2024.info()

<class 'pandas.core.frame.DataFrame'>
Index: 92 entries, AIN to Zambia
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Gold Medal    92 non-null     int64
 1   Silver Medal  92 non-null     int64
 2   Bronze Medal  92 non-null     int64
 3   Total Medals  92 non-null     int64
 4   population    79 non-null     float64
 5   gdpPerCapita  79 non-null     float64
dtypes: float64(2), int64(4)
memory usage: 5.0+ KB

In [18]:
null_values_population_gdp = medals_population_gdp_2024[medals_population_gdp_2024['population'].isnull() &
                                                        medals_population_gdp_2024['gdpPerCapita'].isnull()]
null_values_population_gdp

,Gold Medal,Silver Medal,Bronze Medal,Total Medals,population,gdpPerCapita
country,,,,,,
AIN,1,3,1,5,NaN,NaN
Cabo Verde,0,0,1,1,NaN,NaN
Chinese Taipei,2,0,5,7,NaN,NaN
Czechia,3,0,2,5,NaN,NaN
Côte d'Ivoire,0,0,1,1,NaN,NaN
DPR Korea,0,2,4,6,NaN,NaN
EOR,0,0,1,1,NaN,NaN
Great Britain,14,22,29,65,NaN,NaN
"Hong Kong, China",2,0,2,4,NaN,NaN
IR Iran,3,6,3,12,NaN,NaN
Korea,13,9,10,32,NaN,NaN
Republic of Moldova,0,1,3,4,NaN,NaN
Türkiye,0,3,5,8,NaN,NaN

In [19]:
null_values_population_gdp.shape[0] # 92 - 79 = 13

13

In [20]:
medals_population_gdp_2024.loc['Cabo Verde', 'population'] = 524877
medals_population_gdp_2024.loc['Cabo Verde', 'gdpPerCapita'] = 5178.35607199401

medals_population_gdp_2024.loc['Chinese Taipei', 'population'] = 23213962
medals_population_gdp_2024.loc['Chinese Taipei', 'gdpPerCapita'] = 34589.4423364698

medals_population_gdp_2024.loc['Czechia', 'population'] = 10735859
medals_population_gdp_2024.loc['Czechia', 'gdpPerCapita'] = 30354.3479846373

medals_population_gdp_2024.loc["Côte d'Ivoire", 'population'] = 31934230
medals_population_gdp_2024.loc["Côte d'Ivoire", 'gdpPerCapita'] = 2721.56241124336

medals_population_gdp_2024.loc['DPR Korea', 'population'] = 26498823
medals_population_gdp_2024.loc['DPR Korea', 'gdpPerCapita'] = 572.709761976975

medals_population_gdp_2024.loc['Great Britain', 'population'] = 69138192
medals_population_gdp_2024.loc['Great Britain', 'gdpPerCapita'] = 50554.6919711178

medals_population_gdp_2024.loc['Hong Kong, China', 'population'] = 7414909
medals_population_gdp_2024.loc['Hong Kong, China', 'gdpPerCapita'] = 54859.0683985468

medals_population_gdp_2024.loc['IR Iran', 'population'] = 91567738
medals_population_gdp_2024.loc['IR Iran', 'gdpPerCapita'] = 5069.26358713808

medals_population_gdp_2024.loc['Korea', 'population'] = 51717590
medals_population_gdp_2024.loc['Korea', 'gdpPerCapita'] = 34049.3437532569

medals_population_gdp_2024.loc['Republic of Moldova', 'population'] = 3034961
medals_population_gdp_2024.loc['Republic of Moldova', 'gdpPerCapita'] = 6048.18315622507

medals_population_gdp_2024.loc['Türkiye', 'population'] = 87473805
medals_population_gdp_2024.loc['Türkiye', 'gdpPerCapita'] = 12730.2110614715

In [21]:
null_values_population_gdp = medals_population_gdp_2024[medals_population_gdp_2024['population'].isnull() &
                                                        medals_population_gdp_2024['gdpPerCapita'].isnull()]
null_values_population_gdp

,Gold Medal,Silver Medal,Bronze Medal,Total Medals,population,gdpPerCapita
country,,,,,,
AIN,1,3,1,5,NaN,NaN
EOR,0,0,1,1,NaN,NaN

**EOR** (*Équipe Olympique des Réfugiés*): The French term for the **Refugee Olympic Team**, which consists of athletes who are refugees and compete under the Olympic flag.

**AIN** (*Athlètes Individuels Neutres*): The French term for **Individual Neutral Athletes**, referring to Russian and Belarusian athletes competing without national symbols at the 2024 Paris Olympics due to their countries’ involvement in the Ukraine conflict.

In [23]:
medals_population_gdp_2024 = medals_population_gdp_2024.drop(index=['AIN', 'EOR'])
medals_population_gdp_2024.info()

<class 'pandas.core.frame.DataFrame'>
Index: 90 entries, Albania to Zambia
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Gold Medal    90 non-null     int64
 1   Silver Medal  90 non-null     int64
 2   Bronze Medal  90 non-null     int64
 3   Total Medals  90 non-null     int64
 4   population    90 non-null     float64
 5   gdpPerCapita  90 non-null     float64
dtypes: float64(2), int64(4)
memory usage: 4.9+ KB

In [24]:
medals_population_gdp_2024

,Gold Medal,Silver Medal,Bronze Medal,Total Medals,population,gdpPerCapita
country,,,,,,
Albania,0,0,2,2,2791765.0,9109.291076
Algeria,2,0,1,3,46814308.0,5698.685111
Argentina,1,1,1,3,45696159.0,13223.430880
Armenia,0,3,1,4,2973840.0,8543.835580
Australia,18,19,16,53,26713205.0,67021.160508
...,...,...,...,...,...,...
Uganda,1,1,0,2,50015092.0,1125.860170
Ukraine,3,5,4,12,37860221.0,4990.541392
United States,40,44,42,126,345426571.0,83320.399808
Uzbekistan,8,2,3,13,36361859.0,2693.921672
Zambia,0,0,1,1,21314956.0,1401.457268

In [25]:
folder_path = '../data/processed/'
file_name = 'medals_population_gdp_2024_processed.csv'
full_path = folder_path + file_name
medals_population_gdp_2024.to_csv(full_path)

In [26]:
medal_distribution_2024_processed = pd.read_csv('../data/processed/medals_population_gdp_2024_processed.csv')